var baseDiv = document.createElement('div');
baseDiv.id = "mainDiv";
var heading = document.createElement('h2');
heading.innerText = 'Que No.1  Find Function';
baseDiv.append(heading);
var queDiv = document.createElement('div');
queDiv.innerText = "\nlet arr = [11, 25, 23, 14, 52, 16, 37, 18, 92];\n\n\nfunction Find(arr, MyFunc) {\n    let temp = [];\n    for (let i = 0; i < arr.length; i++) {\n        let Output = MyFunc(arr[i]);\n        if (Output) {\n            temp.push(arr[i]);\n        }\n\n    }\n    return temp;\n}\nconsole.log(Find(arr, number => number < 25));\n\n";
baseDiv.append(queDiv);
var outputhead = document.createElement('h3');
outputhead.id = 'outputDiv';
baseDiv.append(outputhead);
outputhead.innerText = 'Output is [11, 23, 14, 16, 18]';
var line = document.createElement('hr');
line.id = "line";
baseDiv.append(line);
//-----------------chunk----------------------------
var heading = document.createElement('h2');
heading.innerText = 'Que No.2  Chunk Function';
baseDiv.append(heading);
var queDiv = document.createElement('div');
queDiv.innerText = "\nlet ArrElements = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];\n\nfunction Chunk(ArrElements, sizeOfChunk) {\n    let temp = [];\n    let j=0;\nif(sizeOfChunk<=0){\n    return temp;\n}\nwhile(ArrElements.length){\n\ntemp[j++]=ArrElements.splice(0,sizeOfChunk);\n}\nreturn temp;\n\n}\n\nconsole.log(Chunk(ArrElements, 3));\n\n\n";
baseDiv.append(queDiv);
var outputhead = document.createElement('h3');
outputhead.id = 'outputDiv';
baseDiv.append(outputhead);
outputhead.innerText = 'Output is [ [ 1, 2, 3 ], [ 4, 5, 6 ], [ 7, 8, 9 ], [ 10 ] ]';
var line = document.createElement('hr');
line.id = "line";
baseDiv.append(line);
//-------------Filter-----------------------
var heading = document.createElement('h2');
heading.innerText = 'Que No.3  Filter Function';
baseDiv.append(heading);
var queDiv = document.createElement('div');
queDiv.innerText = "\nlet arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];\n\nfunction MyFunc(arr, FilterData) {\n    let temp = [];\n\n    for (let i = 0; i < arr.length; i++) {\n        let Output = FilterData(arr[i]);\n\n        if (Output) {\n            temp.push(arr[i]);\n        }\n\n    }\n    return temp;\n}\n\nconsole.log(MyFunc(arr, element => element % 2 === 0));\n\n\n";
baseDiv.append(queDiv);
var outputhead = document.createElement('h3');
outputhead.id = 'outputDiv';
baseDiv.append(outputhead);
outputhead.innerText = 'Output is [ 2, 4, 6, 8, 10 ]';
var line = document.createElement('hr');
line.id = "line";
baseDiv.append(line);
//----------Reduce-----------------------------------
var heading = document.createElement('h2');
heading.innerText = 'Que No.4  Reduce Function';
baseDiv.append(heading);
var queDiv = document.createElement('div');
queDiv.innerText = "\nlet arrData = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];\n\nfunction Reduce(arrData, MyFunc,accumulator) {\n    for (let i = 0; i < arrData.length; i++) {\n        accumulator = MyFunc(accumulator, arrData[i]);\n    }\n\n    return accumulator;\n}\n\nconsole.log(Reduce(arrData, (sum, n) => sum + n,0));\n\n\n";
baseDiv.append(queDiv);
var outputhead = document.createElement('h3');
outputhead.id = 'outputDiv';
baseDiv.append(outputhead);
outputhead.innerText = 'Output is 55';
var line = document.createElement('hr');
line.id = "line";
baseDiv.append(line);
//--------------Sum-------------------------
var heading = document.createElement('h2');
heading.innerText = 'Que No.5  Sum Function';
baseDiv.append(heading);
var queDiv = document.createElement('div');
queDiv.innerText = "\n\nlet MySum = (arr) => {\n    let sum = 0;\n    for (let i = 0; i < arr.length; i++)\n     {\n        sum = sum + arr[i];\n    }\nreturn sum;\n}\nconsole.log(MySum([11,2,3,4,5]));\n\n\n";
baseDiv.append(queDiv);
var outputhead = document.createElement('h3');
outputhead.id = 'outputDiv';
baseDiv.append(outputhead);
outputhead.innerText = 'Output is 25';
document.body.append(baseDiv);
